name: Build -> Deploy into the Production Server

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]        
    steps:
      - uses: actions/checkout@v2
      - name: prepare .ssh dir
        run: mkdir -p .ssh && chmod 700 .ssh
      - name: ssh key generate
        run: echo "$SSH_KEY" > .ssh/id_rsa && chmod 600 .ssh/id_rsa
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: install packages
        run:  |
          npm install   
          npm install @material-ui/core 
          #  Otherwise, an Error in build Step (Cannot find module: '@material-ui/core/utils'. Make sure this package is installed.)
      - name: build
        run: CI='' npm run build
        # CI = ''
          #  : For prevenging Warnings are seen as Errors as CI purpose. 
      - name: install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp
      - name: deploy with lftp
        run: lftp -e "set net:max-retries 1; set sftp:connect-program \"ssh -a -x -p $SSH_PORT -i .ssh/id_rsa -o StrictHostKeyChecking=no\"; connect sftp://$SSH_USER:@$SSH_HOST; mirror -eR -x .git -x .ssh $BUILD_DIR $HOST_DIR; quit"
        env:       
          BUILD_DIR: build/     
          HOST_DIR: ~/public_html/portfolio-static.conohawing.com
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}